DeportenisUTH/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API.Models;
using DeportenisUTH.Models;
using Database;
using Newtonsoft.Json;
using System.Security.Cryptography;
using System.Web.Services.Description;
using DeportenisUTH.Utils;

namespace DeportenisUTH.Controllers
{
    public class CategoriesController : Controller
    {
        public CategoriesController() 
        {
            //this._orderBy.Add("0", "Description");
            //this._orderBy.Add("1", "LastUpdate");
        }

        // GET: Categories
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult _Edit(API.Models.Category model)    
        {
            API.Catalogs.Category api = new API.Catalogs.Category();           
            int result = 0;
            model.LastUpdated = DateTime.Now;
            model.LastCreated = DateTime.Now;
            if(model.Id == 0)
            {
                result = api.Add(model);
            }
            else
            {
                result = api.UpdateCategory(model);
            }
            return View("Index");



        }
        public ActionResult Create()
        {
            //DeportenisUTH.Models.Category model = new DeportenisUTH.Models.Category();
            API.Models.Category model = new API.Models.Category();

            return View("_Edit",model);
        }
        public ActionResult getCategoriesList()
        {
            // Establecer los valores del grid, para la paginacion, ordenacion, filtrado, busqueda/
            DataTableNetManage objDTNetManage = new DataTableNetManage(Request);

            // Category departments = new Category(this.ambient);
            API.Catalogs.Category category = new API.Catalogs.Category();

            IQueryable<API.Models.Category> queryBrands = category.Query();
           // queryBrands = ExtensionMethods.OrderByField(queryBrands, this._orderBy[objDTNetManage.orderCol], objDTNetManage.bDescending);


            // Obtener el total de registros(recordsTotal) para indicarlos en el grid /
            objDTNetManage.recordsTotal = queryBrands.Count();

            // Filtro por si hay busqueda general /
            if (objDTNetManage.searchVal != "")
            {
                queryBrands = from res in queryBrands where res.Name.Contains(objDTNetManage.searchVal) select res;

            }
            // Obtener el total de registros filtrados(recordsFiltered) para indicarlos en el grid /
            objDTNetManage.recordsFiltered = queryBrands.Count();

            objDTNetManage.setPaginationRange();


            string ElementsSearched = JsonConvert.SerializeObject(queryBrands.ToList().GetRange(objDTNetManage.startFrom, objDTNetManage.lengthGrid));
            string sResult = "{ \"draw\":" + objDTNetManage.draw + ", \"recordsTotal\":" + objDTNetManage.recordsTotal + ",\"recordsFiltered\":" + objDTNetManage.recordsFiltered + ",\"data\":" + ElementsSearched + "}";


            return new ContentResult { Content = sResult, ContentType = "application/json" };
        }
        public ActionResult Delete(int id)
        {
            API.Catalogs.Category api = new API.Catalogs.Category();
            api.Delete(id);
            return View("Index");
        }
        public ActionResult Edit(int id)
        {
            API.Catalogs.Category api = new API.Catalogs.Category();
            API.Models.Category model = new API.Models.Category();
            Database.Category model2 = new Database.Category();
            
             model  = api.Find(id);
            return View("_Edit" , model);
        }
    }



}

DeportenisUTH/Controllers/ProductController.cs
using Database;
using DeportenisUTH.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace DeportenisUTH.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            API.Models.Products model = new API.Models.Products();

            return View("_Edit", model);
        }
        public ActionResult _Edit(API.Models.Products model)
        {
            API.Catalogs.Products api = new API.Catalogs.Products();
            int result = 0;

            model.LastUpdated = DateTime.Now;
            model.LastCreated = DateTime.Now;
            if (model.Id == 0)
            {
                result = api.Add(model);
            }
            else
            {
                result = api.Update(model);
            }
            return View("Index");
        }
        public ActionResult getProductList()
        {
            // Establecer los valores del grid, para la paginacion, ordenacion, filtrado, busqueda/
            DataTableNetManage objDTNetManage = new DataTableNetManage(Request);

            // Category departments = new Category(this.ambient);
            API.Catalogs.Products products = new API.Catalogs.Products();

            IQueryable<API.Models.Products> queryBrands = products.Query();
            // queryBrands = ExtensionMethods.OrderByField(queryBrands, this._orderBy[objDTNetManage.orderCol], objDTNetManage.bDescending);


            // Obtener el total de registros(recordsTotal) para indicarlos en el grid /
             objDTNetManage.recordsTotal = queryBrands.Count();

            // Filtro por si hay busqueda general /
            if (objDTNetManage.searchVal != "")
            {
                queryBrands = from res in queryBrands where res.Name.Contains(objDTNetManage.searchVal) select res;

            }
            // Obtener el total de registros filtrados(recordsFiltered) para indicarlos en el grid /
            objDTNetManage.recordsFiltered = queryBrands.Count();

            objDTNetManage.setPaginationRange();


            string ElementsSearched = JsonConvert.SerializeObject(queryBrands.ToList().GetRange(objDTNetManage.startFrom, objDTNetManage.lengthGrid));
            string sResult = "{ \"draw\":" + objDTNetManage.draw + ", \"recordsTotal\":" + objDTNetManage.recordsTotal + ",\"recordsFiltered\":" + objDTNetManage.recordsFiltered + ",\"data\":" + ElementsSearched + "}";


            return new ContentResult { Content = sResult, ContentType = "application/json" };
        }
        public ActionResult Delete(int id)
        {
            API.Catalogs.Products api = new API.Catalogs.Products();
            api.Delete(id);
            return View("Index");
        }
        public ActionResult Edit(int id)
        {
            API.Catalogs.Products api = new API.Catalogs.Products();
            API.Models.Products model = new API.Models.Products();
            Database.Product model2 = new Database.Product();

            model = api.Find(id);
            return View("_Edit", model);
        }
        public List<SelectListItem> GetCategories(long categoryIdSelected = 0)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            API.Catalogs.Category api = new API.Catalogs.Category();
            List<API.Models.Category> query = api.Query().ToList();
            foreach (var d in query)
            {
                items.Add(new SelectListItem()
                {
                    Text = d.Name,
                    Value = d.Id.ToString(),
                    Selected = categoryIdSelected == 0 ? false : categoryIdSelected == d.Id ? true : false
                });
            }
            return items;


        }
        protected override void Initialize(RequestContext requestContext)
        {

            base.Initialize(requestContext);
            ViewBag.CategoriesList = GetCategories();

        }

    }
}

DeportenisUTH/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using API.Models;
using Database;

namespace DeportenisUTH.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            User model = new User();
            int result = 0;
            API.Catalogs.Users api = new API.Catalogs.Users();
            model.Name = "Javier";
            model.LastName = "Marin";
            model.Email = "jh@email.com";
            model.Password = "12345";
            model.Rol = "Cliente";
            model.LastCreated = DateTime.Now;
            model.LastUpdated = DateTime.Now;
            result = api.Add(model);
            return View();
        }
    }
}

DeportenisUTH/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="../../Content/assets/images/favicon.png">
    <title>DeportenisUTH</title>
    <!-- Bootstrap Core CSS -->
    <link href="../../Content/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- chartist CSS -->
    @*<link href="../../Content/assets/plugins/chartist-js/dist/chartist.min.css" rel="stylesheet">
        <link href="../../Content/assets/plugins/chartist-js/dist/chartist-init.css" rel="stylesheet">
        <link href="../../Content/assets/plugins/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css" rel="stylesheet">*@
    <!--This page css - Morris CSS -->
    <link href="../../Content/assets/plugins/c3-master/c3.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="../../Content/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="../../Content/css/colors/blue.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        <!-- Logo icon --><b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            @*<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrJHrYIQfuyfmYgNr36wuaJzGupOPlobIxxQ" alt="homepage" class="dark-logo" />*@
                            <!-- Light Logo icon -->
                            @*<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrJHrYIQfuyfmYgNr36wuaJzGupOPlobIxxQ" width="150px" height="70px" alt="homepage" class="light-logo" />*@
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text --><span>
                            <!-- dark Logo text -->
                            <!--<img src="../../Content/assets/images/logo-text.png" alt="homepage" class="dark-logo" />-->
                            <!-- Light Logo text -->
                            <!--<img src="../../Content/assets/images/logo-light-text.png" class="light-logo" alt="homepage" />-->
                        </span>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto mt-md-0">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="mdi mdi-menu"></i></a> </li>
                        <li class="nav-item"> <a class="nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->
                    </ul>

                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        @*<div class="page-wrapper">*@
        <!-- ============================================================== -->
        <!-- Container fluid  -->
        <div>
            @RenderBody()
        </div>
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- End Container fluid  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- footer -->
        <!-- ============================================================== -->
        @*<footer class="footer"> © 2023 Jesus Paul Marin Moreno</footer>*@
        <!-- ============================================================== -->
        <!-- End footer -->
        <!-- ============================================================== -->
    </div>
    <aside class="left-sidebar">
        <!-- Sidebar scroll-->
        <div class="scroll-sidebar">
            <!-- User profile -->
            <div class="user-profile" style="background: url(../../Content/assets/images/background/user-info.jpg) no-repeat;">
                <!-- User profile image -->
                @*<div class="profile-img"> <img src="../../Content/assets/images/users/profile.png" alt="user" /> </div>*@
                <!-- User profile text-->
                <div class="profile-text">
                    <div class="dropdown-menu animated flipInY">
                        <a href="#" class="dropdown-item"><i class="ti-user"></i> My Profile</a> <a href="#" class="dropdown-item"><i class="ti-wallet"></i> My Balance</a> <a href="#" class="dropdown-item"><i class="ti-email"></i> Inbox</a>
                        <div class="dropdown-divider"></div> <a href="#" class="dropdown-item"><i class="ti-settings"></i> Account Setting</a>
                    </div>
                </div>
            </div>
            <!-- End User profile text-->
            <!-- Sidebar navigation-->
            <nav class="sidebar-nav">
                <ul id="sidebarnav">

                    <li>
                        <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-gauge"></i><span class="hide-menu">Dashboard </span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li>@Html.ActionLink("Deportenis", "Index", "DeportenisUTH", new { area = "" }, new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-asterisk"></i><span class="hide-menu">Catalogos </span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li>@Html.ActionLink("Categorias", "Index", "Categories", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Productos", "Index", "Product", new { area = "" }, new { @class = "nav-link" })</li>
                        </ul>
                    </li>
                    <li>
                        <a class="has-arrow waves-effect waves-dark" href="#" aria-expanded="false"><i class="mdi mdi-security"></i><span class="hide-menu">Seguridad </span></a>
                        <ul aria-expanded="false" class="collapse">
                            <li>@Html.ActionLink("Roles", "Index", "DeportenisUTH", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink("Usuarios", "Index", "Users", new { area = "" }, new { @class = "nav-link" })</li>

                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- End Sidebar navigation -->
        </div>
        <!-- End Sidebar scroll-->
        <!-- Bottom points-->


    </aside>
    <!-- ============================================================== -->
    <!-- End Page wrapper  -->
    <!-- ============================================================== -->
    @*</div>*@
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="../../Content/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="../../Content/assets/plugins/popper/popper.min.js"></script>
    <script src="../../Content/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="../../Content/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="../../Content/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="../../Content/js/sidebarmenu.js"></script>
    <!--stickey kit -->
    <script src="../../Content/assets/plugins/sticky-kit-master/dist/sticky-kit.min.js"></script>
    <script src="../../Content/assets/plugins/sparkline/jquery.sparkline.min.js"></script>
    <!--Custom JavaScript -->
    <script src="../../Content/js/custom.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!-- chartist chart -->
    <!--c3 JavaScript -->
    <script src="../../Content/assets/plugins/d3/d3.min.js"></script>
    <script src="../../Content/assets/plugins/c3-master/c3.min.js"></script>
    <!-- Chart JS -->
    <script src="../../Content/js/dashboard1.js"></script>
    <!-- ============================================================== -->
    <!-- Style switcher -->
    <!-- ============================================================== -->
    <script src="../../Content/assets/plugins/styleswitcher/jQuery.style.switcher.js"></script>
    <script src="../../Content/assets/plugins/datatables/jquery.dataTables.min.js"></script>


</body>

</html>